AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'Gemfile'
    - 'vendor/**/*'

Metrics/BlockLength:
  Max: 40

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/GuardClause:
  Enabled: false

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
